### DISCUSSION TITLE
OTA update custom server problem

### DISCUSSION THREAD

**Discussion by ptath** [RavenSystem/esp-homekit-devices#1639] [General]
**Detailed steps to reproduce it**
Nginx on port 11080, all files in /haa, accessible via browser

**Logs**
```
0002.650 192.168.1.154-5C89EE: HAA Installer v5.2.2
0002.650 192.168.1.154-5C89EE: 
0002.651 192.168.1.154-5C89EE: 
0002.660 192.168.1.154-5C89EE: - Server http://192.168.2.10/haa
0002.661 192.168.1.154-5C89EE: - Port   11080
0002.661 192.168.1.154-5C89EE: - SSL    no
0002.661 192.168.1.154-5C89EE: 
0002.664 192.168.1.154-5C89EE: Current HAAMAIN installed v0.0.0
0002.665 192.168.1.154-5C89EE: 
0002.665 192.168.1.154-5C89EE: INIT
0004.788 192.168.1.154-5C89EE: ERROR
0004.789 192.168.1.154-5C89EE: Forwarding: http://192.168.2.10/haa/otamain.bin.sec
0004.790 192.168.1.154-5C89EE: ret = 82
0004.790 192.168.1.154-5C89EE: 
0004.790 192.168.1.154-5C89EE: *** NEW CONNECTION
0005.001 192.168.1.154-5C89EE: DNS..ERROR
0005.002 192.168.1.154-5C89EE: Forwarding: http://192.168.2.10/haa/otamain.bin.sec
0005.003 192.168.1.154-5C89EE: ret = 82
```

Any ideas?

**Comment by RavenSystem** [comment]
Remove "http://" part from Custom server field.

**Reply by ptath** [reply]
Thanks, it started

**Reply by Alex-us425** [reply]
скиньте пожалуйста  настройки  пользовательского сервера как все должно выглядеть?

**Reply by ptath** [reply]
```
version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "11080:80"
        volumes:
            - ./www:/usr/share/nginx/html
```

[haa_downloader](https://github.com/RavenSystem/haa/blob/master/haa_downloader.sh)
