### DISCUSSION TITLE
Migrating ESPHome to HAA

### DISCUSSION THREAD

**Discussion by Rahulsharma0810** [RavenSystem/esp-homekit-devices#2106] [MEPLHAA Scripts]
Hi, First of all, thank you for the great work.

I am trying to migrate the ESPhome code for the 6 Channel relay with Feedback(Turn on/off via manual wall switch).

![image](https://github.com/RavenSystem/esp-homekit-devices/assets/9934859/ee247479-6344-4818-982a-bae7470cbcad)

Below is the esphome yaml file attached to GPIO Pins `15,2,4,18,19,21` and with Corresponding GPIO Pins for wall switch  `13,14,27,26,25,32`

I've tried many examples from https://glumb.github.io/haa-configurator/ and some references from Issues. But not even a single relay switch is not working.

If someone, please reference how to make the ESPHome config below work with HAA Firmware. 

```
#LOAD
output:
  - platform: gpio
    id: "light1"
    pin: 15
  - platform: gpio
    id: "light2"
    pin: 2
  - platform: gpio
    id: "light3"
    pin: 4
  - platform: gpio
    id: "light4"
    pin: 18
  - platform: gpio
    id: "light5"
    pin: 19
  - platform: gpio
    id: "light6"
    pin: 21
light:
  - platform: binary
    output: "light1"
    name: "light1"
  - platform: binary
    output: "light2"
    name: "light2"
  - platform: binary
    output: "light3"
    name: "light3"
  - platform: binary
    output: "light4"
    name: "light4"
  - platform: binary
    output: "light5"
    name: "light5"
  - platform: binary
    output: "light6"
    name: "light6"
switch:
  - platform: gpio
    pin: GPIO15
    name: "relay"
    id: relay1
  - platform: gpio
    pin: GPIO2
    name: "relay"
    id: relay2
  - platform: gpio
    pin: GPIO4
    name: "relay"
    id: relay3
  - platform: gpio
    pin: GPIO18
    name: "relay"
    id: relay4
  - platform: gpio
    pin: GPIO19
    name: "relay"
    id: relay5
  - platform: gpio
    pin: GPIO21
    name: "relay"
    id: relay6

#switch

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.turn_on: relay1
    on_release:
      then:
        - switch.turn_off: relay1
  - platform: gpio
    pin:
      number: 14
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.turn_on: relay2
    on_release:
      then:
        - switch.turn_off: relay2
  - platform: gpio
    pin:
      number: 27
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.turn_on: relay3
    on_release:
      then:
        - switch.turn_off: relay3
  - platform: gpio
    pin:
      number: 26
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.turn_on: relay4
    on_release:
      then:
        - switch.turn_off: relay4
  - platform: gpio
    pin:
      number: 25
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.turn_on: relay5
    on_release:
      then:
        - switch.turn_off: relay5
  - platform: gpio
    pin:
      number: 32
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      then:
        - switch.turn_on: relay6
    on_release:
      then:
        - switch.turn_off: relay6

```

I would appreciate any help you can give me.
