### DISCUSSION TITLE
how to covert esphome config.yaml to meplhaa scripts?

### DISCUSSION THREAD

**Discussion by weigeloveu** [RavenSystem/esp-homekit-devices#2202] [MEPLHAA Scripts]
hi bros  i have a config of esphome and dont want to use ha,it very hard for me to edit a meplhaa scripts,any method to covert esphome config.yaml to meplhaa scripts?thanks a lot!

```
substitutions:
  node_name: cmcc-powerboard
  node_id: cmcc_powerboard
  node_name_friendly: ${node_name}
esphome:
  name: ${node_name}
  min_version: 2023.11.4
esp8266:
  board: esp_wroom_02
  restore_from_flash: false  

wifi:
  ap:
    ssid: "${node_id} hotspot"
    password: !secret ap_password

captive_portal:

logger:
    level: DEBUG
api:
  encryption:
    key: !secret api_key
  reboot_timeout: 0s
ota:
  password: !secret ota_password

web_server:
  port: 80
  include_internal: true
  version: 1

#Power button
binary_sensor:
  - platform: gpio
    name: button4
    pin:
      number: 4
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: switch_button

#Power-on indicator
light:
  - platform: binary
    name: "light_power_status_output_gpio5"
    id: light_power_status_output_gpio5
    output: poweron_output_gpio5

output:
  - platform: gpio
    id: output_gpio15
    pin:
      number: 15
      inverted: true

  - id: poweron_output_gpio5
    platform: gpio
    pin:
      number: 5
      inverted: true
button:
  - platform: output
    name: "button_output_gpio15"
    id: button_output_gpio15
    output: output_gpio15
    duration: 50ms
    internal: true

switch:
  #Virtual switches
  - platform: template
    name: switch_button
    id: switch_button
    lambda: |-
      return id(switch_gpio0).state ? true: false;

    turn_on_action:
      - switch.turn_on: switch_gpio0
      - switch.turn_on: switch_gpio12
      - light.turn_on: light_power_status_output_gpio5
    turn_off_action:
      - switch.turn_off: switch_gpio12
      - switch.turn_off: switch_gpio0
      - light.turn_off: light_power_status_output_gpio5
  #Trunk relays
  - platform: gpio
    name: switch_gpio0
    id: switch_gpio0
    pin: 
      number: 0
      inverted: true
    on_turn_on:
      then:
        - button.press: button_output_gpio15
    on_turn_off:
        - button.press: button_output_gpio15
  
  #Shunt relays
  - platform: gpio
    name: switch_gpio12
    id: switch_gpio12
    pin: 
      number: 12
      inverted: true
    on_turn_on:
      then:
        - button.press: button_output_gpio15
    on_turn_off:
        - button.press: button_output_gpio15
#restart
  - platform: restart
    name: "${node_name_friendly}-Restart"
    id: ${node_id}_restart
  #reset
  - platform: factory_reset
    name: ${node_name}-factory-reset
    id: ${node_id}_factory_reset
```
