### ISSUE TITLE
RGBWW Bulbs

### ISSUE THREAD

**Issue by rasod** [RavenSystem/esp-homekit-devices#800]
Is there a way to configure a RGB bulb that has 2 white channels?

I got some RGB bulbs and flashed (1.6.4) one using Tuya convert. I configured using what I think is the correct pins for the channels, however the bulb doesn’t really change colours and when you turn off the bulb it just changes colour temperature. I think this is because the configuration is only turning of one of the white channels off and the other is remaining on always

Configuration I have used:

```{"a":[{"t":30,"r":4,"g":12,"v":14,"w":5,"s":1}]}```

Below is the Home Assistant ESP Home Configuration for what I think is the correct bulb

```
esphome:
  name: garagebulb1
  platform: ESP8266
  board: esp01_1m

output:
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
    max_power: 0.7

  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
    max_power: 0.7

  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    max_power: 0.7

  - platform: esp8266_pwm
    id: output_wwhite
    pin: GPIO13
    max_power: 0.65

  - platform: esp8266_pwm
    id: output_cwhite
    pin: GPIO5
    max_power: 0.65

light:
  - platform: rgbww
    name: "garagelight1"
    id: light_rgb
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cwhite
    warm_white: output_wwhite
    cold_white_color_temperature: 5000 K
    warm_white_color_temperature: 2000 K
    effects:
      - strobe:
      - flicker:
      - random:
# Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON
```
